layout_spectrum: 0.9086022
typography_spectrum: 0.5528173
color:
  saturation: 0.5
  brandStrength: 0.1885597
  lightness: 0.4982079
  rhythmicContrast: 0.4731183
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Dormidoporcafe
